### ISSUE TITLE
Feature request: Queue of URLs/Playlist

### ISSUE THREAD

**Issue by OevreFlataeker** [billybanana80/FreevineGUI#1]
Hi,

it would be great, if you could add a feature which allows to put multiple URLs in a queue and download them all. Entries should be possible to be from various services and potentially also with different settings for resolution and scope. 

Thanks for considering!

**Comment by billybanana80** [comment]
stabbedbybrick has added this functionality to the underlying Python code, so I am testing this within my GUI at the moment. All being good it will be included in my next release shortly.

**Comment by OevreFlataeker** [comment]
Perfect! Thank you so much!
