### ISSUE TITLE
Download full season missing the input for season number

### ISSUE THREAD

**Issue by OevreFlataeker** [billybanana80/FreevineGUI#3]
Please see here: https://github.com/stabbedbybrick/freevine/issues/43
Seems that selection in the UI is not asking for the actual season number so the download fails. 
Could you please integrate this? Thanks!

**Comment by billybanana80** [comment]
You need to type the season number at the beginning of the series URL before you hit Go. If I included them in a dropdown selection for example, it's as much effort from a user perspective to choose it than it is to type it, so I haven't considered it to date.

![Screenshot 2023-12-29 094504](https://github.com/billybanana80/FreevineGUI/assets/149659663/4caed622-d943-48d5-bbbd-a184a86e8409)
