### ISSUE TITLE
Pressing 'Go' tries to open a Python IDE

### ISSUE THREAD

**Issue by dp247** [billybanana80/FreevineGUI#4]
This _may_ be specific to my setup, but whenever I try to run a command, Windows pops up asking me to choose a program to open the .py file:
![image](https://github.com/billybanana80/FreevineGUI/assets/9065463/28798f0d-9247-405d-a30e-3962f7eec420)

I have a feeling its something to do with 'python' being omitted from the complete command, would it be possible to add an option to prepend this in, please?

**Comment by OevreFlataeker** [comment]
Please check your "%PATHEXT%" env variable and check if ".py" is present there or add it if not present. This should solve the problem without further changes.

**Comment by dp247** [comment]
That'll be what I'm missing, thanks for the shout!
